routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Auth::routes();

Route::get('verify/{token}', '\App\Http\Controllers\Auth\RegisterController@verify')->name('account.verify');

Route::get('/rebuild', function () {
    Artisan::call('config:clear');
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    if (isset($_SERVER['HTTP_HOST'])) {
        $root = (isset($_SERVER['HTTPS']) ? "https://" : "http://") . $_SERVER['HTTP_HOST'];
        $root .= str_replace(basename($_SERVER['SCRIPT_NAME']), '', $_SERVER['SCRIPT_NAME']);
        return "<script> window.location.href = '" . $root . "'; </script>";
    }
})->name('app.rebuild');

Route::group(['middleware' => ['SessionTimeout', 'XSS', 'auth']], function ($router) {

    Route::get('/', function () {
        $user = \Auth::user();
        if ($user->can("view_dashboards")) {
            return redirect()->route('dashboards.index');
        } else {
            return redirect()->route('profiles.index');
        }
    })->name("home");

    Route::get('/home', function () {
        return redirect()->route('home');
    });

    Route::resource('dashboards', '\App\Http\Controllers\Main\DashboardController');
    Route::resource('profiles', '\App\Http\Controllers\Main\ProfileController');

    Route::group(['prefix' => 'product'], function () {
        Route::resource('brands', '\App\Http\Controllers\Main\Product\BrandController');
        Route::resource('groups', '\App\Http\Controllers\Main\Product\GroupController');
        Route::resource('categories', '\App\Http\Controllers\Main\Product\CategoryController');
        Route::resource('items', '\App\Http\Controllers\Main\Product\ItemController');
        Route::resource('product_images', '\App\Http\Controllers\Main\Product\ProductImageController');
    });

    Route::group(['prefix' => 'reference'], function () {
        Route::resource('banks', '\App\Http\Controllers\Main\Reference\BankController');
        Route::resource('customers', '\App\Http\Controllers\Main\Reference\CustomerController');
        Route::resource('stakeholders', '\App\Http\Controllers\Main\Reference\StakeHolderController');
        Route::resource('suppliers', '\App\Http\Controllers\Main\Reference\SupplierController');
    });

    Route::group(['prefix' => 'transaction'], function () {
        Route::resource('transaction_sales', '\App\Http\Controllers\Main\Transaction\SaleController');
        Route::resource('transaction_purchases', '\App\Http\Controllers\Main\Transaction\PurchaseController');
        Route::resource('transaction_fees', '\App\Http\Controllers\Main\Transaction\FeeController');
        Route::get('invoice/{id}/{collections}', '\App\Http\Controllers\Main\Transaction\InvoiceController@preview')->name("invoice.preview");
        Route::get('invoice_loader', '\App\Http\Controllers\Main\Transaction\InvoiceController@previewLoader')->name("invoice.loader");
    });

    Route::resource('reports', '\App\Http\Controllers\Main\ReportController');

    Route::group(['prefix' => 'setting'], function () {
        Route::resource('settings', '\App\Http\Controllers\Main\Setting\SettingController');
        Route::resource('audits', '\App\Http\Controllers\Main\Setting\AuditController');
        Route::resource('users', '\App\Http\Controllers\Main\Setting\UserController');
        Route::resource('roles', '\App\Http\Controllers\Main\Setting\RoleController');
    });


});

app/Http/Controllers/Main/ReportController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\MainController;
use Illuminate\Http\Request;
use App\Models\Report;

class ReportController extends MainController{

    const REPORT_SALE = 1;
    const REPORT_PURCHASE = 2;
    const REPORT_FEE = 3;

    public function __construct(){
        $this->layout = "main.transaction.report";
        $this->route = "reports";
        $this->title = "Report";
        $this->subtitle = "report transaction";
        $this->model = new Report;
        $this->dataTableModel = base64_encode(Report::class);
    }

    public function show($id){
        $types = array(1, 2, 3);
        $this->data["title"] = $this->title;
        $this->data["subtitle"] = $this->subtitle;
        $this->data["route"] = $this->route;
        if(in_array($id, $types)){
            if($id == self::REPORT_SALE){
                return $this->__render__page($this->layout.".sale", $this->data);
            }
            if($id == self::REPORT_PURCHASE){
                return $this->__render__page($this->layout.".purchase", $this->data);    
            }
            if($id == self::REPORT_FEE){
                return $this->__render__page($this->layout.".fee", $this->data);
            }
        }else{
            return abort(404);  
        }
    }

    public function create(){
        return abort(404);  
    }

    public function store(Request $request){
        return abort(404);  
    }

    public function edit($id){
        return abort(404);  
    }

    public function update($id, Request $request){
        $types = array(1, 2, 3);
        if(in_array($id, $types)){
            $report_type = $request->get("report_type");
            $filter = $request->get("filter");
            $date_start = $request->get("date_start");
            $date_end = $request->get("date_end");
            $data = Report::getTransaction($report_type, $filter, $date_start, $date_end);
            if($id == self::REPORT_SALE){
                if((int) $filter == 1){
                    return view("main.report.sale.period", ["data"=> $data]);
                }
                if((int) $filter == 2){
                    return view("main.report.sale.product", ["data"=> $data]);
                }
                if((int) $filter == 3){
                    return view("main.report.sale.customer", ["data"=> $data]);
                }
            }
            if($id == self::REPORT_PURCHASE){
                if((int) $filter == 1){
                    return view("main.report.purchase.period", ["data"=> $data]);
                }
                if((int) $filter == 2){
                    return view("main.report.purchase.product", ["data"=> $data]);
                }
                if((int) $filter == 3){
                    return view("main.report.purchase.supplier", ["data"=> $data]);
                }
            }
            if($id == self::REPORT_FEE){
                if((int) $filter == 1){
                    return view("main.report.fee.period", ["data"=> $data]);
                }
                if((int) $filter == 2){
                    return view("main.report.fee.stakeholder", ["data"=> $data]);
                }
            }
        }else{
            return abort(404);  
        }
    }

    public function destroy($id){
        return abort(404);  
    }

}

app/Http/Controllers/Main/Transaction/FeeController.php
<?php

namespace App\Http\Controllers\Main\Transaction;

use App\Http\Controllers\MainController;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\Transaction;
use App\Models\Stakeholder;

class FeeController extends MainController{

    const TYPE = 3;
    const CODE = "TFEE";

    public function __construct(){
        $this->layout = "main.transaction.fee";
        $this->route = "transaction_fees";
        $this->title = "Fee";
        $this->subtitle = "fee invoice management";
        $this->model = new Transaction;
        $this->dataTableModel = base64_encode(Transaction::class);
    }

    protected function createValidation(){
        return [
            'stakeholder_id' => 'required',
            'invoice_date' => 'required',
            'invoice_number' => 'required|unique:transactions',
            'grandtotal' => 'required',
        ];
    }

    protected function updateValidation($id){
        return [
            'stakeholder_id' => 'required',
            'invoice_date' => 'required',
            'invoice_number' => 'required|unique:transactions,invoice_number,' . $id,
            'grandtotal' => 'required',
        ];
    }

    public function create(){
        $model = array(
            "invoice_number"=> Transaction::createInvoiceNumber(self::TYPE, self::CODE)
        );
        $this->data["stakeholders"] = Stakeholder::orderBy("name", "ASC")->get();
        $this->data["model"] = (object) $model;
        $this->data["title"] = $this->title;
        $this->data["subtitle"] = $this->subtitle;
        $this->data["route"] = $this->route;
        return $this->__render__page($this->layout.".form", $this->data);
     }
 
    public function edit($id){
         $this->data["stakeholders"] = Stakeholder::orderBy("name", "ASC")->get();
         return parent::edit($id);
    }

    public function store(Request $request){
        $rules = $this->createValidation();
        $validator = Validator::make($request->all(), $rules);
        if ($validator->fails()) {
            return redirect()->back()->withErrors($validator->errors())->withInput();
        }else{
            $post = $request->all();
            $post["invoice_number"] = Transaction::createInvoiceNumber(self::TYPE, self::CODE);
            $data = $this->model->create($post);
            $id = $data->id;
            return redirect()->route($this->route.".show", ["id"=>$id])->with('success', self::SUCCESS_MESSAGE_CREATED);
        }
    }

    
}

app/Http/Controllers/Main/Transaction/InvoiceController.php
<?php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace App\Http\Controllers\Main\Transaction;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Models\Transaction;
use App\Models\Customer;
use App\Models\Supplier;
use App\Models\Stakeholder;
use App\Models\Bank;

class InvoiceController extends BaseController{

    public function previewLoader(){
        return null;
    }

    public function preview($id, $collections){
        $transaction = Transaction::where("id", $id)->first();
        if(is_null($transaction)){
            return abort(404);  
        }
        $data = json_decode(base64_decode($collections));
        $data->transaction->is_purchased = $transaction->is_purchased;
        $data->transaction->record_date = $transaction->created_at;
        $data->transaction->notes = $transaction->notes;
        $data->transaction->user_id = $transaction->user_id;

        if(isset($data->transaction->customer_id)){
            $data->customer = Customer::where("id", $data->transaction->customer_id)->first();
        }else{
            $data->customer = null;
        }

        if(isset($data->transaction->supplier_id)){
            $data->supplier = Supplier::where("id", $data->transaction->supplier_id)->first();
        }else{
            $data->supplier = null;
        }

        if(isset($data->transaction->stakeholder_id)){
            $data->stakeholder = Stakeholder::where("id", $data->transaction->stakeholder_id)->first();
        }else{
            $data->stakeholder = null;
        }

        if(isset($data->transaction->bank_id)){
            $data->bank = Bank::where("id", $data->transaction->bank_id)->first();
        }else{
            $data->bank = null;
        }

        if((int) $transaction->type == 1){
            return view("main.transaction.sale.invoice", ["data" => $data]);
        }else if((int) $transaction->type == 2){
            return view("main.transaction.purchase.invoice", ["data" => $data]);
        }else if((int) $transaction->type == 3){
            return view("main.transaction.fee.invoice", ["data" => $data]);
        }else{
            return abort(404);  
        }
        
    }


}

app/Http/Controllers/Main/Transaction/PurchaseController.php
<?php

namespace App\Http\Controllers\Main\Transaction;

use App\Http\Controllers\MainController;
use Illuminate\Http\Request;
use App\Models\Transaction;
use App\Models\TransactionDetail;
use App\Models\Supplier;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Group;
use App\Models\Bank;


class PurchaseController extends MainController{

    const TYPE = 2;
    const CODE = "TPRC";

    public function __construct(){
        $this->layout = "main.transaction.purchase";
        $this->route = "transaction_purchases";
        $this->title = "Purchase";
        $this->subtitle = "purchase invoice management";
        $this->model = new Transaction;
        $this->dataTableModel = base64_encode(Transaction::class);
    }

    public function create(){
        $invoice_number = Transaction::createInvoiceNumber(self::TYPE, self::CODE);
        $invoice_date = date("Y-m-d");
        $user_id = \Auth::user()->id;
        $data = array(
            'user_id'=> $user_id,
            'is_purchased'=> 0,
            'type'=> self::TYPE,
            'invoice_date'=> $invoice_date,
            'invoice_number'=> $invoice_number,
            'total_items'=> 0,
            'subtotal'=> 0,
            'tax'=> 0,
            'discount'=> 0,
            'grandtotal'=> 0,
            'cash'=> 0,
            'change'=> 0
        );
        $transaction = Transaction::create($data);
        return redirect()->route($this->route.".edit", ["id"=>$transaction->id]);
    }

    public function edit($id){

        $model = $this->model->where("id", $id)
            ->where("type", self::TYPE)
            ->where("is_purchased", 0)
            ->first();

        if(is_null($model)){
            return abort(404);  
        }

        $this->data["title"] = $this->title;
        $this->data["subtitle"] = $this->subtitle;
        $this->data["model"] = $model;
        $this->data["banks"] = Bank::orderBy("name", "ASC")->get();
        $this->data["suppliers"] = Supplier::orderBy("name", "ASC")->get();
        $this->data["brands"] = Brand::orderBy("name", "ASC")->get();
        $this->data["groups"] = Group::orderBy("name", "ASC")->get();
        $this->data["route"] = $this->route;
        return $this->__render__page($this->layout.".form", $this->data);
    }

    public function show($id){
        $model = $this->model->where("id", $id)->first();
        if(is_null($model)){
            return abort(404);  
        }

        $details = TransactionDetail::where("transaction_id", $id)->get();

        $collections = array();
        $collections["transaction"] = $model;
        $collections["details"] = array();
        
        if(count($details) > 0){
            $temp = array();
            foreach($details as $row){
                $temp[] = array(
                    "product_id"=> $row->product_id,
                    "product_sku"=> $row->Product->sku,
                    "product_name"=>  $row->Product->name,
                    "price"=> $row->price,
                    "qty"=> $row->qty,
                    "total"=> $row->total
                );
            }
            $collections["details"] = $temp;
        }
        
        $this->data["title"] = $this->title;
        $this->data["subtitle"] = $this->subtitle;
        $this->data["model"] = $model;
        $this->data["details"] = $details;
        $this->data["collections"] = base64_encode(json_encode($collections));
        $this->data["route"] = $this->route;
        return $this->__render__page($this->layout.".show", $this->data);
    }
   

    public function update($id, Request $request){
        if($request->get("data-invoice")){
            $updated = Transaction::saveInvoice(self::TYPE, $id, $request->get("data-invoice"));
            return redirect()->route($this->route.".show", ["id"=>$id])->with('success', 'You transaction have been successful!.');
        }else{
            return abort(404);  
        }
    }

}

resources/views/main/transaction/report/fee.blade.php
@extends('layouts.app')
@section('title') {{ $title }} Fee @endsection
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $title }}
        <small>{{ $subtitle }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('') }}"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#">Report</a></li>
        <li class="active">Fee</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    @include('layouts.alert')
    <!-- Default box -->
    <div class="box {{ CommonHelper::getBoxTheme() }}">
        <div class="box-header with-border">
            <h3 class="box-title">
                <i class="fa fa-file-text-o"></i>&nbsp;Show report fee
           </h3>
        </div>
        <form class="form-horizontal" method="POST" action="{{ route('reports.update', ['id'=> 3]) }}" target="_blank">
            {{ csrf_field() }}
            {!! method_field('patch') !!}
            <input type="hidden" name="report_type" value="3" />
            <div class="box-body">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Filter By</label>
                    <div class="col-sm-8">
                        <select name="filter" id="filter" class="form-control select2" required="required">
                            <option disabled selected>-- Choose Filter --</option>
                            <option value="1">Period</option>
                            <option value="2">Stakeholder</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date Start</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_start" name="date_start" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date End</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_end" name="date_end" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="clearfix">
                    <div class="pull-left">
                        <button type="submit" class="btn btn-info btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Show Report'>
                            <i class="fa fa-search"></i>&nbsp;Show Report
                        </button>
                    </div>
                    <div class="pull-right">
                        <button type="reset" class="btn btn-warning btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Reset'>
                            <i class="fa fa-refresh"></i>&nbsp;Reset Form
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div><!-- /.box -->
</section><!-- /.content -->

@endsection

resources/views/main/transaction/report/purchase.blade.php
@extends('layouts.app')
@section('title') {{ $title }} Purchase Order @endsection
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $title }}
        <small>{{ $subtitle }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('') }}"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#">Report</a></li>
        <li class="active">Purchase</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    @include('layouts.alert')
    <!-- Default box -->
    <div class="box {{ CommonHelper::getBoxTheme() }}">
        <div class="box-header with-border">
            <h3 class="box-title">
                <i class="fa fa-file-text-o"></i>&nbsp;Show report purchase order
           </h3>
        </div>
        <form class="form-horizontal" method="POST" action="{{ route('reports.update', ['id'=> 2]) }}" target="_blank">
            {{ csrf_field() }}
            {!! method_field('patch') !!}
            <input type="hidden" name="report_type" value="2" />
            <div class="box-body">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Filter By</label>
                    <div class="col-sm-8">
                        <select name="filter" id="filter" class="form-control select2" required="required">
                            <option disabled selected>-- Choose Filter --</option>
                            <option value="1">Period</option>
                            <option value="2">Product</option>
                            <option value="3">Supplier</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date Start</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_start" name="date_start" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date End</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_end" name="date_end" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="clearfix">
                    <div class="pull-left">
                        <button type="submit" class="btn btn-info btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Show Report'>
                            <i class="fa fa-search"></i>&nbsp;Show Report
                        </button>
                    </div>
                    <div class="pull-right">
                        <button type="reset" class="btn btn-warning btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Reset'>
                            <i class="fa fa-refresh"></i>&nbsp;Reset Form
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div><!-- /.box -->
</section><!-- /.content -->

@endsection

resources/views/main/transaction/report/sale.blade.php
@extends('layouts.app')
@section('title') {{ $title }} Sale Order @endsection
@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        {{ $title }}
        <small>{{ $subtitle }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('') }}"><i class="fa fa-home"></i> Home</a></li>
        <li><a href="#">Report</a></li>
        <li class="active">Sale</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    @include('layouts.alert')
    <!-- Default box -->
    <div class="box {{ CommonHelper::getBoxTheme() }}">
        <div class="box-header with-border">
            <h3 class="box-title">
                <i class="fa fa-file-text-o"></i>&nbsp;Show report sale order
           </h3>
        </div>
        <form class="form-horizontal" method="POST" action="{{ route('reports.update', ['id'=> 1]) }}" target="_blank">
            {{ csrf_field() }}
            {!! method_field('patch') !!}
            <input type="hidden" name="report_type" value="1" />
            <div class="box-body">
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Filter By</label>
                    <div class="col-sm-8">
                        <select name="filter" id="filter" class="form-control select2" required="required">
                            <option disabled selected>-- Choose Filter --</option>
                            <option value="1">Period</option>
                            <option value="2">Product</option>
                            <option value="3">Customer</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date Start</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_start" name="date_start" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
                <div class="form-group">
                    <label for="" class="col-sm-2 control-label">Date End</label>
                    <div class="col-sm-8">
                        <input type="text" class="form-control input-datepicker" id="date_end" name="date_end" value="{{ date('Y-m-d')  }}" required="required">
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <div class="clearfix">
                    <div class="pull-left">
                        <button type="submit" class="btn btn-info btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Show Report'>
                            <i class="fa fa-search"></i>&nbsp;Show Report
                        </button>
                    </div>
                    <div class="pull-right">
                        <button type="reset" class="btn btn-warning btn-sm" data-toggle='tooltip' data-placement='top'  data-original-title='Reset'>
                            <i class="fa fa-refresh"></i>&nbsp;Reset Form
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div><!-- /.box -->
</section><!-- /.content -->

@endsection